### ISSUE TITLE
Mini-Sprint for shared code infrastructure for the scientific python stack

### ISSUE THREAD

**Issue by bsipocz** [numfocus/summit2022-unconference#11]
This will be scheduled during the whole duration of the unconference track and will be an opportunity to form interproject teams to share requirements and solutions and resources for tasks we all need to address.

Subtopics and agenda TBA, we are thinking along these lines:

 - devstats
 - documentation testing tools
 - documentation and tutorial rendering and website themes
 - automated benchmarking solutions
 

lead by @jarrodmillman and @bsipocz

**Comment by pllim** [comment]
Happened 2022-09-22 1:30 pm.

But I am keeping this open in case this is meant to be a two-day thing.

**Comment by pllim** [comment]
Happened 2022-09-23 2 pm.
