### ISSUE TITLE
Continuous integration tools and processes

### ISSUE THREAD

**Issue by IAlibay** [numfocus/summit2022-unconference#12]
Recent years have seen both large-scale shifts in CI platforms (i.e. away from Travis, towards GH Actions) and a need to cover a wider range of architectures (e.g. osx-arm64). This has brought interesting challenges for project maintainers in charge of CI infrastructure.

I would therefore like to propose a chat on how we can best share experiences going forward, communicating the availability of new tools and best practices on how to efficiently leverage them, not only within NumFOCUS projects but also to smaller projects who may not have the bandwidth / expertise to keep up with these changes.

(Note: happy to close this if this is somehow covered by #11)

**Comment by pllim** [comment]
Will happen 2022-09-22 4:30 pm
