### ISSUE TITLE
Improving communication among NF projects

### ISSUE THREAD

**Issue by IAlibay** [numfocus/summit2022-unconference#13]
My take is that outside conferences, it's very easy for NF projects to exist in complete isolation from each other, often leading to wasted collaborative opportunities and duplication of efforts.

Supplementing the "interoperability among projects" session, I would like to propose a chat on potential solutions to this communication issue.

**Comment by IAlibay** [comment]
Being discussed in the Thursday morning session. The unconference would concentrate on keeping the conversation going and seeing if we can put together some more concrete plans that we can agree to participate in.

**Comment by pllim** [comment]
Will happen 2022-09-22 2:40 pm
