### ISSUE TITLE
Open-Source Science Initiative

### ISSUE THREAD

**Issue by alexy** [numfocus/summit2022-unconference#14]
- Discuss the best way to enable science with OSS, including:
- Interest Groups in various disciplines, such as
   - Chemistry
   - Climate and Sustainability
   - Healthcare and Life Science
- Interest Groups for cross-cutting concerns, such as
   - Reproducibility
   - Map of Science

**Comment by pllim** [comment]
Thanks!

Map of Science is the same one mentioned in #15?

**Comment by pllim** [comment]
Happened 2022-09-23 2 pm.
