### ISSUE TITLE
Map of Science

### ISSUE THREAD

**Issue by alexy** [numfocus/summit2022-unconference#15]
One of the goals of OSSci is to create a Map of Science with OSS.
That is, map all of OSS used by scientists to their disciplines.
This requires a Map of Science itself, using proper ontologies accepted in each area of science.
Then there're questions of finding all the OSS:
- top-down from papers
- top-down from curated lists and communities
- bottom-up with ML classifiers 

Let's discuss all of this and more!

**Comment by pllim** [comment]
Is it just me or this sounds similar to the package listing that Scientific Python wanted to do, @jarrodmillman ?

**Comment by pllim** [comment]
Merged with #14 given they both can happen in same session and would have similar participants. Thanks for your understanding!
