### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by pllim** [numfocus/summit2022-unconference#7]
Depending on the actual demographics of attendees who are interested to join this one, we might have to split this into language-specific ones, unless it is about something that can handle multiple languages like conda-forge.

**Comment by FrancescAlted** [comment]
The Blosc team is definitely interested in packaging, mainly for Python, but C is also interesting for us.

**Comment by IAlibay** [comment]
This is something I be interested in, from a mostly Python perspective. I'd be particularly interested in sharing experiences in automated deployment and ensuring the long term stability of releases.

**Comment by pllim** [comment]
Merged with #18
